spring:
  application:
    name: java-xah
app:
  domain: example.com
  port: 25565
  xray-version: 25.10.15
  hy2-version: 2.6.5
  argo-version: 2025.10.0
  uuid: 2584b733-9095-4bec-a7d5-62b473540f7a
  argo-domain:
  argo-token:
  reality-public-key:
  reality-private-key:
  reality-short-id:
  remarks-prefix:
