spring:
  application:
    name: java-xah
app:
  domain: example.com
  port: 10008
  uuid:
  xray-version: 25.10.15
  hy2-version: 2.6.5
  argo-version: 2025.10.0
  argo-domain: xxx.trycloudflare.com
  argo-token:
  reality-public-key:
  reality-private-key:
  reality-short-id:
  remarks-prefix: vevc
